name: Daily Mojing Image Download

on:
  # 每天UTC时间0:05运行（北京时间上午8:05）
  schedule:
    - cron: '5 0 * * *'
  # 也支持手动触发
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run download script
        run: |
          python tools/download_mojing_tjb.py
      
      - name: Check for changes
        id: git-check
        run: |
          if ! git diff --quiet M9A/api/images/; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "检测到图片变化"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "图片无变化"
          fi
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add M9A/api/images/
          git commit -m "chore: update mojing daily image [$(date +'%Y-%m-%d')]"
          git push
