name: Daily Activity Update

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activities:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Activity Update Script
        run: |
          python src/main.py
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *.json
          git commit -m "Auto-update activities data - $(date -u '+%Y-%m-%d %H:%M:%S') UTC" || echo "No changes to commit"
          git push || echo "Nothing to push"
